import { StyleSheet } from 'react-native';

export const styles = StyleSheet.create({
  rootContainer: {
    flex: 1,
    backgroundColor: '#3a3535',
    alignItems: 'center',
  },
  listContainer: {
    width: '100%',
    flex: 1,
    paddingBottom: 10,
    alignItems: 'center',
  },
  drillItemContainer: {
    marginTop: 10,
    flexDirection: 'row',
    justifyContent: 'space-between',
    borderRadius: 2,
    shadowColor: 'black',
    shadowRadius: 10,
    width: '100%',
    alignItems: 'center',
  },
  leftContainer: {
    flexDirection: 'row',
    paddingLeft: 10,
  },
  rightContainer: {
    flexDirection: 'row',
    paddingRight: 10,
  },
  indexContainer: {
    alignItems: 'center',
    justifyContent: 'center',
    borderRadius: 2,
    backgroundColor: '#f4f4f4',
    height: 50,
    margin: 10,
  },
  indexText: {
    color: '#3a3535',
    margin: 10,
    fontSize: 20,
    fontFamily: 'System',
    fontWeight: '500',
  },
  titleContainer: {
    alignItems: 'center',
    justifyContent: 'center',
    borderRadius: 2,
    backgroundColor: '#f4f4f4',
    width: 150,
    minHeight: 50,
    maxHeight: 90,
  },
  titleText: {
    color: '#3a3535',
    padding: 10,
    fontSize: 20,
    fontFamily: 'System',
    fontWeight: '500',
    textAlign: 'center',
  },
  durationContainer: {
    alignItems: 'center',
    justifyContent: 'center',
    borderRadius: 2,
    backgroundColor: '#3a3535',
    height: 50,
    marginTop: 10,
    marginBottom: 10,
  },
  durationText: {
    color: '#f4f4f4',
    margin: 10,
    fontSize: 20,
    fontFamily: 'System',
    fontWeight: '500',
  },
  viewDrillButton: {
    alignItems: 'center',
    justifyContent: 'center',
    borderRadius: 25,
    width: 40,
    height: 50,
    marginTop: 10,
    marginBottom: 10,
  },
  removeDrillButton: {
    alignItems: 'center',
    justifyContent: 'center',
    borderRadius: 25,
    width: 40,
    height: 50,
    margin: 10,
  },
  addDrillButton: {
    alignItems: 'center',
    marginTop: 5,
    justifyContent: 'center',
    flexDirection: 'row',
    backgroundColor: '#3a3535',
    borderWidth: 2,
    borderRadius: 20,
    shadowColor: 'black',
    shadowRadius: 3,
    height: 70,
    width: '90%',
  },
  doneButton: {
    alignItems: 'center',
    marginTop: 10,
    justifyContent: 'center',
    flexDirection: 'row',
    backgroundColor: 'green',
    borderWidth: 2,
    borderRadius: 20,
    shadowColor: 'black',
    shadowRadius: 3,
    height: 70,
    width: '90%',
  },
  doneButtonText: {
    color: '#f4f4f4',
    fontFamily: 'System',
    fontSize: 20,
  },
});
