import { StyleSheet } from 'react-native';

export const styles = StyleSheet.create({
  rootContainer: {
    flex: 1,
    backgroundColor: '#3a3535',
    alignItems: 'center',
  },
  settingsButtonsContainer: {
    alignItems: 'center',
    paddingTop: 40,
  },
  primaryButtonContainer: {
    borderWidth: 1,
    borderColor: '#f4f4f4',
    borderStyle: 'solid',
    borderRadius: 6,
    backgroundColor: 'black',
    margin: 20,
    justifyContent: 'center',
    shadowColor: 'black',
    shadowOpacity: 0.8,
    elevation: 6,
    shadowRadius: 15,
    shadowOffset: { width: 1, height: 10 },
    marginTop: 30,
  },
  secondaryButtonContainer: {
    borderRadius: 6,
    backgroundColor: '#ff7315',
    justifyContent: 'center',
    margin: 30,
    shadowColor: 'black',
    shadowOpacity: 0.8,
    elevation: 6,
    shadowRadius: 15,
    shadowOffset: { width: 1, height: 10 },
  },
  primaryButtonText: {
    color: '#ff7315',
    margin: 10,
    textTransform: 'uppercase',
    fontWeight: '600',
    fontSize: 15,
  },
  secondaryButtonText: {
    color: '#f4f4f4',
    margin: 10,
    textTransform: 'uppercase',
    fontWeight: '600',
    fontSize: 15,
  },
  inputTitle: {
    color: '#f4f4f4',
    fontSize: 15,
    marginTop: 20,
  },
  changePasswordInput: {
    color: 'black',
    backgroundColor: 'white',
    borderRadius: 3,
    fontSize: 17,
    width: 200,
    marginTop: 2,
    padding: 5,
  },
  errorText: {
    maxWidth: 200,
    color: 'red',
    paddingTop: 5,
    paddingBottom: 5,
    paddingLeft: 1,
  },
  changePasswordButton: {
    backgroundColor: '#f4f4f4',
    borderRadius: 3,
  },
  changePasswordButtonText: {
    color: '#ff7315',
    fontSize: 15,
    margin: 8,
    fontWeight: '600',
  },
});
